In [3]:
from rewarder import Rewarder
import json
import pandas as pd
from tqdm import tqdm

In [7]:
## example df
df = pd.read_csv('./data/ap/expanded_and_labeled_queries_with_pubmed_ap_n100_200candidates.csv')
df = df.sample(10)

In [8]:
def calculate_reward(rewarder: Rewarder, base_query_column='Q_name', expanded_query_colum='new_q'):
    def eval(row):
        base_query = row[base_query_column]        
        new_query = row[expanded_query_colum]
        return rewarder.reward_one(new_query, base_query)
    return eval

In [10]:
metric = 'recall'
at_n = 100
rewarder = Rewarder(
        "./data/cord_qrels.json", n_results=at_n, metric=metric
    )

tqdm.pandas()
df['new_query_recall'] = df.progress_apply(calculate_reward(rewarder), axis=1)
df

100%|██████████| 10/10 [00:13<00:00,  1.36s/it]

,index,Q_name,candidate,new_q,base_reward,new_reward,label,new_query_recall
14664,39,coronavirus heart impacts,current,coronavirus heart impacts current,0.000355,0.000000,0,0.000000
6892,18,coronavirus public datasets,disease,coronavirus public datasets disease,0.000000,0.000000,0,0.000000
2718,6,COVID inflammatory response,receptor,COVID inflammatory response receptor,0.000000,0.000000,0,0.000000
14162,37,coronavirus outside body,territory,coronavirus outside body territory,0.001175,0.000000,0,0.000000
1723,3,coronavirus response to weather changes,infection,coronavirus response to weather changes infection,0.001608,0.002048,1,0.014286
910,2,coronavirus social distancing impact,damage,coronavirus social distancing impact damage,0.000000,0.000000,0,0.000000
16933,46,coronavirus hydroxychloroquine,study,coronavirus hydroxychloroquine study,0.000000,0.000000,0,0.000000
1219,3,coronavirus response to weather changes,virtual,coronavirus response to weather changes virtual,0.001608,0.000000,0,0.000000
11142,29,serological tests for coronavirus,research,serological tests for coronavirus research,0.000000,0.000000,0,0.000000
13506,36,impact of masks on coronavirus transmission,focusing,impact of masks on coronavirus transmission fo...,0.000000,0.000000,0,0.000000